#ifndef RTCTRL_VISION_IMAGE_FORMAT_H
#define RTCTRL_VISION_IMAGE_FORMAT_H

/* Platform-owned values. UNKNOWN means unspecified/unsupported, never a guessed
 * conversion. These enums are not Linux V4L2 constants or a wire ABI. */
enum rtctrl_pixel_format {
    RTCTRL_PIXEL_UNKNOWN = 0,
    RTCTRL_PIXEL_GRAY8,
    RTCTRL_PIXEL_RGB24,
    RTCTRL_PIXEL_BGR24,
    RTCTRL_PIXEL_NV12,
    RTCTRL_PIXEL_NV21,
    RTCTRL_PIXEL_YUYV,
    RTCTRL_PIXEL_UYVY
};
enum rtctrl_colorspace {
    RTCTRL_COLOR_UNKNOWN = 0,
    RTCTRL_COLOR_SRGB,
    RTCTRL_COLOR_REC709,
    RTCTRL_COLOR_BT2020,
    RTCTRL_COLOR_SMPTE170M,
    RTCTRL_COLOR_SMPTE240M,
    RTCTRL_COLOR_OPRGB,
    RTCTRL_COLOR_DCI_P3,
    RTCTRL_COLOR_BT470_M,
    RTCTRL_COLOR_BT470_BG,
    RTCTRL_COLOR_RAW
};
enum rtctrl_quantization {
    RTCTRL_RANGE_UNKNOWN = 0,
    RTCTRL_RANGE_LIMITED,
    RTCTRL_RANGE_FULL
};
enum rtctrl_transfer_function {
    RTCTRL_TRANSFER_UNKNOWN = 0,
    RTCTRL_TRANSFER_LINEAR,
    RTCTRL_TRANSFER_SRGB,
    RTCTRL_TRANSFER_REC709,
    RTCTRL_TRANSFER_SMPTE240M,
    RTCTRL_TRANSFER_OPRGB,
    RTCTRL_TRANSFER_DCI_P3,
    RTCTRL_TRANSFER_SMPTE2084
};
enum rtctrl_ycbcr_encoding {
    RTCTRL_YCBCR_UNKNOWN = 0,
    RTCTRL_YCBCR_BT709,
    RTCTRL_YCBCR_BT601,
    RTCTRL_YCBCR_BT2020,
    RTCTRL_YCBCR_BT2020_CONSTANT,
    RTCTRL_YCBCR_SMPTE240M,
    RTCTRL_YCBCR_XV601,
    RTCTRL_YCBCR_XV709
};
#endif
