cmake_minimum_required(VERSION 3.16)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    project(camera_capture LANGUAGES C)
    add_subdirectory(../../src/vision ${CMAKE_CURRENT_BINARY_DIR}/vision)
endif()
add_executable(rtctrl_camera_capture main.c)
target_link_libraries(rtctrl_camera_capture PRIVATE rtctrl_vision_v4l2)
target_compile_options(rtctrl_camera_capture PRIVATE -Wall -Wextra -Wpedantic)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    install(TARGETS rtctrl_camera_capture RUNTIME DESTINATION bin)
endif()
