set(CMAKE_SYSTEM_NAME Linux)

# Compiler ABI checks run in nested try_compile projects. Explicitly propagate
# the platform inputs so the toolchain remains reusable for every target.
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    RTCTRL_TARGET_TRIPLE
    RTCTRL_SYSROOT)

if(NOT DEFINED RTCTRL_TARGET_TRIPLE)
  message(FATAL_ERROR "Set RTCTRL_TARGET_TRIPLE, for example aarch64-linux-gnu")
endif()

set(CMAKE_C_COMPILER "${RTCTRL_TARGET_TRIPLE}-gcc")
set(CMAKE_CXX_COMPILER "${RTCTRL_TARGET_TRIPLE}-g++")

if(DEFINED RTCTRL_SYSROOT)
  set(CMAKE_SYSROOT "${RTCTRL_SYSROOT}")
  set(CMAKE_FIND_ROOT_PATH "${RTCTRL_SYSROOT}")
  set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
  set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()
