set(CMAKE_SYSTEM_NAME Linux)

# Compiler ABI checks run in nested try_compile projects. Explicitly propagate
# the platform inputs so the toolchain remains reusable for every target.
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
        RTCTRL_TARGET_TRIPLE
        RTCTRL_TOOLCHAIN_BIN
        RTCTRL_SYSROOT)

if(NOT DEFINED RTCTRL_TARGET_TRIPLE)
    message(FATAL_ERROR "Set RTCTRL_TARGET_TRIPLE, for example aarch64-linux-gnu")
endif()

if(DEFINED RTCTRL_TOOLCHAIN_BIN AND NOT RTCTRL_TOOLCHAIN_BIN STREQUAL "")
    if(NOT IS_ABSOLUTE "${RTCTRL_TOOLCHAIN_BIN}")
        message(FATAL_ERROR "RTCTRL_TOOLCHAIN_BIN must be an absolute path")
    endif()
    set(RTCTRL_COMPILER_PREFIX "${RTCTRL_TOOLCHAIN_BIN}/${RTCTRL_TARGET_TRIPLE}")
else()
    set(RTCTRL_COMPILER_PREFIX "${RTCTRL_TARGET_TRIPLE}")
endif()

set(CMAKE_C_COMPILER "${RTCTRL_COMPILER_PREFIX}-gcc")
set(CMAKE_CXX_COMPILER "${RTCTRL_COMPILER_PREFIX}-g++")

if(DEFINED RTCTRL_SYSROOT)
    set(CMAKE_SYSROOT "${RTCTRL_SYSROOT}")
    set(CMAKE_FIND_ROOT_PATH "${RTCTRL_SYSROOT}")
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()
