# Products supply defaults; each adapter remains an explicit independent choice.
set(rtctrl_linux_default OFF)
set(rtctrl_posix_default OFF)
if(NOT RTCTRL_PRODUCT STREQUAL "control-sim")
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(rtctrl_linux_default ON)
    endif()
    if(UNIX)
        set(rtctrl_posix_default ON)
    endif()
endif()
option(RTCTRL_ENABLE_POSIX_SHM "Build POSIX shared-memory mapping adapter" ${rtctrl_posix_default})
option(RTCTRL_ENABLE_KERNEL_MAILBOX "Build Linux kernel mailbox adapter and UAPI codec" ${rtctrl_linux_default})
option(RTCTRL_ENABLE_SERIAL "Build Linux serial/RS485 adapter" ${rtctrl_linux_default})
option(RTCTRL_ENABLE_SOCKETCAN "Build Linux SocketCAN adapter" ${rtctrl_linux_default})
foreach(adapter KERNEL_MAILBOX SERIAL SOCKETCAN)
    if(RTCTRL_ENABLE_${adapter} AND NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
        message(FATAL_ERROR "${adapter} adapter requires Linux; disable RTCTRL_ENABLE_${adapter}")
    endif()
endforeach()
if(RTCTRL_ENABLE_POSIX_SHM AND NOT UNIX)
    message(FATAL_ERROR "POSIX shared memory requires a POSIX platform")
endif()

set(rtctrl_v4l2_default OFF)
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(rtctrl_v4l2_default ON)
endif()
option(RTCTRL_ENABLE_V4L2 "Build the Linux V4L2 camera adapter" ${rtctrl_v4l2_default})
if(RTCTRL_ENABLE_V4L2 AND NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "V4L2 requires Linux; disable RTCTRL_ENABLE_V4L2")
endif()
