# Check the complete target closure at configure time, including PUBLIC and
# PRIVATE links. Compatibility umbrellas are allowed only at composition roots.
function(rtctrl_check_closure target allowed visited)
    if("${target}" IN_LIST visited)
        return()
    endif()
    if(NOT "${target}" IN_LIST allowed)
        message(FATAL_ERROR "Architecture violation: forbidden dependency ${target}")
    endif()
    list(APPEND visited "${target}")
    if(NOT TARGET "${target}")
        return()
    endif()
    get_target_property(imported "${target}" IMPORTED)
    if(imported)
        return()
    endif()
    foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
        get_target_property(dependencies "${target}" ${property})
        if(dependencies)
            foreach(dependency IN LISTS dependencies)
                # Static libraries expose private links this way.
                string(REGEX REPLACE "^\\$<LINK_ONLY:(.*)>$" "\\1" dependency "${dependency}")
                rtctrl_check_closure("${dependency}" "${allowed}" "${visited}")
            endforeach()
        endif()
    endforeach()
endfunction()
if(RTCTRL_BUILD_CONTROL)
    rtctrl_check_closure(rtctrl_runtime
        "rtctrl_runtime;rtctrl_contracts;rtctrl_options;rtctrl_timer;rtctrl_safety;Threads::Threads;atomic" "")
    rtctrl_check_closure(rtctrl_bridge "rtctrl_bridge;rtctrl_contracts;rtctrl_options" "")
    rtctrl_check_closure(rtctrl_control "rtctrl_control;rtctrl_contracts;rtctrl_options" "")
endif()
if(RTCTRL_BUILD_VISION)
    rtctrl_check_closure(rtctrl_vision_v4l2 "rtctrl_vision_v4l2" "")
endif()
